# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
