# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-04 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='text',
        ),
    ]
